name: Destroy SQS

on:
  workflow_dispatch:

jobs:
  destroy-infra:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      #AWS CREDENTIALS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      #Terraform execution
      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Destroy
        run:  |
          cd terraform
          terraform destroy -auto-approve